# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TreeSL
                                 A QGIS plugin
 plugin which helps in reaforestation, urban greening and agroforestry
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-29
        copyright            : (C) 2024 by Nickson 
        email                : bsc-com-34-@unima.ac.mw
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TreeSL class from file TreeSL.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TreeSL import TreeSL
    return TreeSL(iface)
